// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagementSystemCore.Models;

namespace StudentManagementSystemCore.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StudentManagementSystemCore.Models.Admin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LoginName");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.HasKey("ID");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("StudentManagementSystemCore.Models.Courses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Duration");

                    b.Property<decimal?>("Fees");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("SisId");

                    b.Property<int?>("StudentID");

                    b.Property<int?>("TeacherID");

                    b.Property<string>("Tool_Name");

                    b.HasKey("Id");

                    b.HasIndex("StudentID");

                    b.HasIndex("TeacherID");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("StudentManagementSystemCore.Models.Platforms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactEmail");

                    b.Property<string>("Description");

                    b.Property<string>("Guid");

                    b.Property<string>("Name");

                    b.Property<string>("ProductFamilyCode");

                    b.Property<string>("Url");

                    b.Property<string>("Version");

                    b.HasKey("Id");

                    b.ToTable("Platform");
                });

            modelBuilder.Entity("StudentManagementSystemCore.Models.ResourceLinks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CoursesId");

                    b.Property<string>("CustomProperties");

                    b.Property<string>("Description");

                    b.Property<int?>("PlatformsId");

                    b.Property<string>("Title");

                    b.Property<int?>("ToolId");

                    b.HasKey("Id");

                    b.HasIndex("CoursesId");

                    b.HasIndex("PlatformsId");

                    b.HasIndex("ToolId");

                    b.ToTable("ResourceLinks");
                });

            modelBuilder.Entity("StudentManagementSystemCore.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Course");

                    b.Property<string>("Education");

                    b.Property<decimal?>("Fees");

                    b.Property<string>("Name");

                    b.Property<string>("Personal_info");

                    b.HasKey("ID");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("StudentManagementSystemCore.Models.Teacher", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Course");

                    b.Property<string>("Education");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("StudentManagementSystemCore.Models.Tools", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustomProperties");

                    b.Property<string>("DeepLinkingLaunchUrl");

                    b.Property<string>("DeploymentId");

                    b.Property<int>("IdentityServerClientId");

                    b.Property<string>("LaunchUrl");

                    b.Property<string>("LoginUrl");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Tools");
                });

            modelBuilder.Entity("StudentManagementSystemCore.Models.Courses", b =>
                {
                    b.HasOne("StudentManagementSystemCore.Models.Student")
                        .WithMany("Courses")
                        .HasForeignKey("StudentID");

                    b.HasOne("StudentManagementSystemCore.Models.Teacher")
                        .WithMany("Courses")
                        .HasForeignKey("TeacherID");
                });

            modelBuilder.Entity("StudentManagementSystemCore.Models.ResourceLinks", b =>
                {
                    b.HasOne("StudentManagementSystemCore.Models.Courses")
                        .WithMany("ResourceLinks")
                        .HasForeignKey("CoursesId");

                    b.HasOne("StudentManagementSystemCore.Models.Platforms")
                        .WithMany("ResourceLinks")
                        .HasForeignKey("PlatformsId");

                    b.HasOne("StudentManagementSystemCore.Models.Tools", "Tool")
                        .WithMany()
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
